"""Unit tests for ExportService (brief generation, markdown formatting, and fallbacks)."""

from unittest.mock import MagicMock, patch

from app.models.schemas import AnalysisResponse, DocumentType, RiskFlag, RiskSeverity
from app.services.export_service import ExportService


class TestExportService:
    """Test lawyer preparation brief generation and structure."""

    def _make_dummy_analysis(self) -> AnalysisResponse:
        return AnalysisResponse(
            document_id="dummy-doc-123",
            document_type=DocumentType.RENTAL,
            summary="This is a residential rental agreement for an apartment in Mumbai.",
            risk_score=40,
            risk_level="medium",
            risk_flags=[
                RiskFlag(
                    clause_text="Tenant shall forfeit all deposit upon early vacation.",
                    severity=RiskSeverity.HIGH,
                    reason="Total forfeiture of deposit is unlawful under model tenancy rules.",
                    category="deposit_forfeiture",
                    legal_reference="Maharashtra Rent Control Act",
                )
            ],
            key_terms={"monthly_rent": "25000 INR", "security_deposit": "100000 INR"},
            parties=["Landlord A", "Tenant B"],
            dates=["01-01-2025"],
            amounts=["25,000 INR", "1,00,000 INR"],
            statute_references=["Maharashtra Rent Control Act"],
            next_steps=["Discuss deposit clause with lawyer"],
        )

    def test_generate_brief_with_gemini_success(self) -> None:
        """Brief should include Gemini-generated overview, unusual items, and questions."""
        analysis = self._make_dummy_analysis()
        mock_gemini = MagicMock()
        mock_gemini.generate_with_document.return_value = {
            "document_overview": "Overview generated by AI.",
            "unusual_findings": ["Unreasonable security deposit forfeiture."],
            "questions_for_lawyer": ["Is the deposit forfeiture clause legally enforceable?"],
        }

        with patch("app.services.export_service.get_gemini_service", return_value=mock_gemini):
            service = ExportService()
            brief = service.generate_brief(
                document_text="Sample text",
                analysis=analysis,
                language="en",
            )

            assert "# Lawyer Preparation Brief" in brief
            assert "⚠️ **Disclaimer**" in brief
            assert "## Document Type: Rental/Lease Agreement" in brief
            assert "Overview generated by AI." in brief
            assert "Is the deposit forfeiture clause legally enforceable?" in brief
            assert "🔴 HIGH" in brief

    def test_generate_brief_fallback_when_gemini_fails(self) -> None:
        """When Gemini fails, brief should fall back to analysis data and default questions."""
        analysis = self._make_dummy_analysis()
        mock_gemini = MagicMock()
        mock_gemini.generate_with_document.side_effect = Exception("Service unavailable")

        with patch("app.services.export_service.get_gemini_service", return_value=mock_gemini):
            service = ExportService()
            brief = service.generate_brief(
                document_text="Sample text",
                analysis=analysis,
                language="en",
            )

            assert "# Lawyer Preparation Brief" in brief
            assert "This is a residential rental agreement for an apartment in Mumbai." in brief
            assert "Questions to Ask Your Lawyer" in brief
            assert len(brief) > 200

    def test_default_questions_per_document_type(self) -> None:
        """Each document type should have relevant default questions."""
        analysis = self._make_dummy_analysis()
        service = ExportService()
        rental_qs = service._get_default_questions(DocumentType.RENTAL, analysis)
        assert any("deposit" in q.lower() for q in rental_qs)

        emp_qs = service._get_default_questions(DocumentType.EMPLOYMENT, analysis)
        assert any("notice period" in q.lower() or "non-compete" in q.lower() for q in emp_qs)

        consumer_qs = service._get_default_questions(DocumentType.CONSUMER, analysis)
        assert any("consumer forum" in q.lower() or "limitation" in q.lower() for q in consumer_qs)
