"""Export service: generates lawyer-prep brief for download."""

import logging
from datetime import datetime

from pydantic import BaseModel, Field

from app.models.schemas import AnalysisResponse, DocumentType, RiskSeverity
from app.services.gemini_service import get_gemini_service

logger = logging.getLogger(__name__)


class LawyerBriefSection(BaseModel):
    """A section of the lawyer-prep brief."""

    heading: str = Field(description="Section heading")
    content: str = Field(description="Section content in plain language")


class LawyerBrief(BaseModel):
    """Schema for the Gemini-generated lawyer brief."""

    document_overview: str = Field(description="What the document is about (2-3 sentences)")
    unusual_findings: list[str] = Field(description="List of unusual or concerning items")
    questions_for_lawyer: list[str] = Field(description="Specific questions to ask a lawyer")


BRIEF_SYSTEM_PROMPT = """You are helping an ordinary person prepare for a meeting with a lawyer
or legal aid clinic. Generate a clear, organized brief that:
1. Summarizes what the document says in plain language
2. Lists what's unusual or concerning about it
3. Provides specific, actionable questions to ask the lawyer

Write for someone with no legal background. Be specific and practical."""


class ExportService:
    """Generates downloadable lawyer-prep briefs."""

    def generate_brief(
        self,
        document_text: str,
        analysis: AnalysisResponse,
        language: str = "en",
        chat_history: list[dict[str, str]] | None = None,
    ) -> str:
        """Generate a one-page lawyer-prep brief.

        Args:
            document_text: The original document text.
            analysis: The analysis results.
            language: Output language.

        Returns:
            Formatted brief as markdown string.
        """
        # Try Gemini-enhanced brief
        gemini_brief = self._generate_gemini_brief(document_text, analysis, language, chat_history)

        # Build the final brief
        brief_parts: list[str] = []

        # Header
        brief_parts.append("# Lawyer Preparation Brief")
        brief_parts.append(f"**Generated by Nyaya Sahayak** | {datetime.now().strftime('%d %B %Y')}")
        brief_parts.append("")
        brief_parts.append("> ⚠️ **Disclaimer**: This brief is for informational purposes only and "
                          "does not constitute legal advice. Please discuss all points with your "
                          "lawyer or legal aid clinic.")
        brief_parts.append("")

        # Document Overview
        type_names = {
            DocumentType.RENTAL: "Rental/Lease Agreement",
            DocumentType.EMPLOYMENT: "Employment/Gig-Work Agreement",
            DocumentType.CONSUMER: "Consumer Dispute/Notice",
            DocumentType.UNKNOWN: "Legal Document",
        }
        doc_type_name = type_names.get(analysis.document_type, "Legal Document")

        brief_parts.append(f"## Document Type: {doc_type_name}")
        brief_parts.append("")

        if gemini_brief:
            brief_parts.append(gemini_brief.get("document_overview", analysis.summary))
        else:
            brief_parts.append(analysis.summary)
        brief_parts.append("")

        # Key Details
        brief_parts.append("## Key Details")
        if analysis.parties:
            brief_parts.append(f"- **Parties**: {', '.join(analysis.parties[:5])}")
        if analysis.dates:
            brief_parts.append(f"- **Important Dates**: {', '.join(analysis.dates[:5])}")
        if analysis.amounts:
            brief_parts.append(f"- **Amounts**: {', '.join(analysis.amounts[:5])}")
        for key, value in analysis.key_terms.items():
            display_key = key.replace("_", " ").title()
            brief_parts.append(f"- **{display_key}**: {value}")
        brief_parts.append("")

        # Risk Flags
        if analysis.risk_flags:
            brief_parts.append("## Unusual or Concerning Items")
            brief_parts.append("")

            severity_icons = {
                RiskSeverity.HIGH: "🔴 HIGH",
                RiskSeverity.MEDIUM: "🟡 MEDIUM",
                RiskSeverity.LOW: "🔵 LOW",
            }

            for flag in analysis.risk_flags:
                icon = severity_icons.get(flag.severity, "⚪")
                brief_parts.append(f"### [{icon}] {flag.category.replace('_', ' ').title()}")
                brief_parts.append(f"**What it says**: \"{flag.clause_text[:200]}\"")
                brief_parts.append(f"**Why it matters**: {flag.reason}")
                if flag.legal_reference:
                    brief_parts.append(f"**Legal reference**: {flag.legal_reference}")
                brief_parts.append("")

        # Gemini-enhanced unusual findings
        if gemini_brief and gemini_brief.get("unusual_findings"):
            brief_parts.append("### Additional Observations")
            for finding in gemini_brief["unusual_findings"]:
                brief_parts.append(f"- {finding}")
            brief_parts.append("")

        # Questions for Lawyer
        brief_parts.append("## Questions to Ask Your Lawyer")
        brief_parts.append("")

        if gemini_brief and gemini_brief.get("questions_for_lawyer"):
            for i, question in enumerate(gemini_brief["questions_for_lawyer"], 1):
                brief_parts.append(f"{i}. {question}")
        else:
            # Generate fallback questions based on document type
            questions = self._get_default_questions(analysis.document_type, analysis)
            for i, question in enumerate(questions, 1):
                brief_parts.append(f"{i}. {question}")
        brief_parts.append("")

        # Footer
        brief_parts.append("---")
        brief_parts.append("*This brief was generated to help you prepare for a legal consultation. "
                          "Bring this document along with the original agreement to your meeting.*")

        return "\n".join(brief_parts)

    def _generate_gemini_brief(
        self,
        document_text: str,
        analysis: AnalysisResponse,
        language: str,
        chat_history: list[dict[str, str]] | None = None,
    ) -> dict | None:
        """Use Gemini to generate enhanced brief content."""
        try:
            gemini = get_gemini_service()

            risk_summary = "\n".join(
                f"- [{f.severity.value.upper()}] {f.reason}"
                for f in analysis.risk_flags
            )

            lang_instruction = ""
            if language == "hi":
                lang_instruction = "\nCRITICAL: You MUST write the ENTIRE response (overview, unusual findings, questions) in Hindi. Do not use English."

            history_text = ""
            if chat_history:
                history_parts = ["\n--- RECENT CHAT CLARIFICATIONS ---"]
                for msg in chat_history:
                    role = "User" if msg.get("role") == "user" else "Assistant"
                    content = msg.get("content", "")
                    history_parts.append(f"{role.upper()}: {content}")
                history_text = "\n".join(history_parts) + "\n\n"

            prompt = (
                f"Document type: {analysis.document_type.value}\n"
                f"Summary: {analysis.summary}\n"
                f"Risk flags found:\n{risk_summary}\n\n"
                f"{history_text}"
                "Based on this analysis AND any new facts/clarifications from the chat history above, generate:\n"
                "1. A 2-3 sentence overview of what this document/situation is about, incorporating any updated facts from the user.\n"
                "2. A list of unusual or concerning items (beyond what's already flagged)\n"
                "3. Specific, practical questions this person should ask their lawyer\n\n"
                "Use markdown bolding (**text**) to highlight the most important parts.\n"
                f"{lang_instruction}"
            )

            return gemini.generate_with_document(
                prompt=prompt,
                document_text=document_text[:30000],
                system_instruction=BRIEF_SYSTEM_PROMPT,
                response_schema=LawyerBrief,
                temperature=0.3,
            )
        except Exception as e:
            logger.error("Gemini brief generation failed: %s", e)
            return None

    def _get_default_questions(
        self,
        document_type: DocumentType,
        analysis: AnalysisResponse,
    ) -> list[str]:
        """Generate default questions based on document type and findings."""
        questions: list[str] = []

        if document_type == DocumentType.RENTAL:
            questions.extend([
                "Is the security deposit amount within the legal limit for my state?",
                "Are the eviction grounds in this agreement consistent with the Rent Control Act?",
                "What are my rights if the landlord doesn't return the security deposit?",
                "Is the rent escalation clause enforceable?",
                "What should I document before moving in to protect my deposit?",
            ])
        elif document_type == DocumentType.EMPLOYMENT:
            questions.extend([
                "Is the non-compete clause enforceable in India?",
                "What are my rights regarding the notice period?",
                "Are the termination terms fair and reciprocal?",
                "What happens to my unpaid salary or benefits if I leave?",
                "Is the IP assignment clause overly broad?",
            ])
        elif document_type == DocumentType.CONSUMER:
            questions.extend([
                "Should I file with the District, State, or National Consumer Forum?",
                "What evidence do I need to strengthen my complaint?",
                "Can I file online through e-Daakhil?",
                "What compensation can I reasonably claim?",
                "Is there a time limit for filing my complaint?",
            ])
        else:
            questions.extend([
                "What are the key obligations this document places on me?",
                "Are any clauses one-sided or potentially unenforceable?",
                "What are my options if the other party breaches this agreement?",
            ])

        # Add questions specific to risk flags
        for flag in analysis.risk_flags:
            if flag.severity == RiskSeverity.HIGH:
                questions.append(
                    f"Regarding the {flag.category.replace('_', ' ')} clause — {flag.reason}. "
                    "Is this enforceable, and what should I do about it?"
                )

        return questions[:10]  # Cap at 10 questions
