"""Rights and legal aid routes.

Returns curated data from /data files — never generated ad hoc by the model.
"""

import json
import logging
from pathlib import Path

from fastapi import APIRouter, Query, Request, Response
from slowapi import Limiter
from slowapi.util import get_remote_address

from app.config import settings
from app.models.schemas import DocumentType, LegalAidInfo, RightsResponse

logger = logging.getLogger(__name__)
router = APIRouter(tags=["rights"])
limiter = Limiter(key_func=get_remote_address)

# Cache loaded data
_rights_cache: dict[str, dict] = {}
_legal_aid_cache: dict[str, dict] = {}


def _load_json_data(file_path: Path) -> dict | list:
    """Load and cache JSON data from file."""
    try:
        return json.loads(file_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        logger.warning("Data file not found: %s", file_path)
        return {}
    except json.JSONDecodeError as e:
        logger.error("Invalid JSON in %s: %s", file_path, e)
        return {}


def _get_rights_data(doc_type: str) -> dict:
    """Get rights checklist data for a document type."""
    if doc_type not in _rights_cache:
        file_path = settings.data_dir / "statutes" / f"{doc_type}_rights.json"
        data = _load_json_data(file_path)
        _rights_cache[doc_type] = data if isinstance(data, dict) else {}
    return _rights_cache[doc_type]


def _get_legal_aid_data() -> dict:
    """Get legal aid contact and eligibility data."""
    if "main" not in _legal_aid_cache:
        file_path = settings.data_dir / "legal_aid" / "legal_aid.json"
        data = _load_json_data(file_path)
        _legal_aid_cache["main"] = data if isinstance(data, dict) else {}
    return _legal_aid_cache["main"]


@router.get("/rights", response_model=RightsResponse)
@limiter.limit("20/minute")
async def get_rights(
    request: Request,
    response: Response,
    doc_type: DocumentType = Query(..., description="Document/situation type"),
    state: str = Query(..., min_length=2, max_length=100, description="Indian state name"),
) -> RightsResponse:
    """Get rights checklist and legal aid information.

    Data is sourced from curated files in /data — not generated by the AI model.
    Contact details should be verified with respective authorities before relying on them.
    """
    response.headers["Cache-Control"] = "public, max-age=3600, stale-while-revalidate=86400"
    rights_data = _get_rights_data(doc_type.value)
    legal_aid_data = _get_legal_aid_data()

    # Get rights for this document type
    rights_list = rights_data.get("rights", [])
    if not rights_list:
        rights_list = _get_default_rights(doc_type)

    # Get forum info
    forum_info = _get_forum_info(doc_type, state, rights_data, legal_aid_data)

    # Get legal aid eligibility
    eligibility = legal_aid_data.get("nalsa_eligibility", {})
    eligible_categories = eligibility.get("categories", _get_default_nalsa_categories())

    # Build contact info
    contact_info = _get_contact_info(doc_type, state, legal_aid_data)

    legal_aid = LegalAidInfo(
        eligible_categories=eligible_categories,
        forum=forum_info["forum"],
        forum_description=forum_info["description"],
        contact_info=contact_info,
        online_portal=forum_info.get("portal"),
        filing_process=forum_info.get("process", ""),
    )

    return RightsResponse(
        document_type=doc_type,
        state=state,
        rights=rights_list,
        legal_aid=legal_aid,
    )


def _get_forum_info(
    doc_type: DocumentType,
    state: str,
    rights_data: dict,
    legal_aid_data: dict,
) -> dict[str, str]:
    """Get the appropriate legal forum based on document type and state."""
    forum_map: dict[DocumentType, dict[str, str]] = {
        DocumentType.RENTAL: {
            "forum": "Rent Controller / Rent Control Court",
            "description": (
                "The Rent Controller is the authority designated under your state's Rent Control Act "
                "to handle disputes between landlords and tenants, including issues related to "
                "eviction, rent increases, and security deposit disputes."
            ),
            "portal": None,
            # TODO: verify against respective state Rent Control Act provisions
            "process": (
                "1. File an application before the Rent Controller of the area where the property is located. "
                "2. Include details of the tenancy, the dispute, and relief sought. "
                "3. Attach copies of the rental agreement and any correspondence. "
                "4. The Rent Controller will issue notice to the other party and schedule a hearing."
            ),
        },
        DocumentType.EMPLOYMENT: {
            "forum": "Labour Commissioner / Industrial Tribunal",
            "description": (
                "The Labour Commissioner's office handles complaints related to employment disputes, "
                "unpaid wages, wrongful termination, and violations of labour laws. For disputes "
                "involving gig workers, the relevant authority may vary by state."
            ),
            "portal": None,
            # TODO: verify state-specific labour department portal URLs
            "process": (
                "1. File a complaint at the Labour Commissioner's office in your district. "
                "2. The office will attempt conciliation between you and your employer. "
                "3. If conciliation fails, the matter may be referred to the Industrial Tribunal. "
                "4. For wage complaints, you can also approach the Authority under the Payment of Wages Act."
            ),
        },
        DocumentType.CONSUMER: {
            "forum": "Consumer Disputes Redressal Forum (Consumer Court)",
            "description": (
                "Under the Consumer Protection Act, 2019, consumers can file complaints at three levels: "
                "District Forum (claims up to ₹1 crore), State Commission (₹1-10 crore), "
                "and National Commission (above ₹10 crore)."
            ),
            "portal": "https://edaakhil.nic.in",
            "process": (
                "1. File online through e-Daakhil (https://edaakhil.nic.in) or in person at your District Consumer Forum. "
                "2. Pay the prescribed fee (based on claim amount; nil for claims up to ₹5 lakh). "
                "3. Attach the bill/receipt, complaint letter, and any evidence of deficiency. "
                "4. The Forum will issue notice to the opposite party within 21 days. "
                "5. Both parties present their case; the Forum aims to dispose within 3-5 months."
            ),
        },
    }

    info = forum_map.get(doc_type, {
        "forum": "Appropriate Legal Authority",
        "description": "Please consult a legal professional to determine the correct forum.",
        "process": "",
    })

    return info


def _get_contact_info(
    doc_type: DocumentType,
    state: str,
    legal_aid_data: dict,
) -> dict[str, str]:
    """Get contact information for the relevant authority."""
    # Try to find state-specific DLSA contact
    dlsa_contacts = legal_aid_data.get("dlsa_contacts", {})
    state_lower = state.lower().strip()

    state_contact = dlsa_contacts.get(state_lower, {})

    contacts: dict[str, str] = {}

    if state_contact:
        contacts.update(state_contact)
    else:
        # Default NALSA contact
        contacts = {
            "authority": "National Legal Services Authority (NALSA)",
            "address": "12/11, Jam Nagar House, Shahjahan Road, New Delhi - 110011",
            "phone": "011-23382778",
            "website": "https://nalsa.gov.in",
            "note": f"TODO: verify DLSA contact for {state}. Please search for your District Legal Services Authority.",
        }

    # Add type-specific portals
    if doc_type == DocumentType.CONSUMER:
        contacts["e_daakhil_portal"] = "https://edaakhil.nic.in"
        contacts["consumer_helpline"] = "1800-11-4000 (National Consumer Helpline)"

    return contacts


def _get_default_rights(doc_type: DocumentType) -> list[str]:
    """Get default rights checklist when data file is not available."""
    rights_map: dict[DocumentType, list[str]] = {
        DocumentType.RENTAL: [
            "You have the right to a written rental agreement with clear terms.",
            "Security deposit cannot exceed the limit set by your state's Rent Control Act.",
            "The landlord must provide reasonable notice before eviction (as per state law).",
            "Essential services (water, electricity) cannot be cut off to force eviction.",
            "You have the right to essential repairs being carried out by the landlord.",
            "Rent cannot be increased arbitrarily — check your state's provisions on permissible increases.",
            # TODO: verify specific state-wise deposit caps against respective Rent Control Acts
        ],
        DocumentType.EMPLOYMENT: [
            "You have the right to a written employment contract or offer letter.",
            "Wages must be paid on time as per the Payment of Wages Act.",
            "Post-employment non-compete clauses are generally unenforceable in India (Section 27, Indian Contract Act).",
            "You are entitled to the notice period specified in your contract, or payment in lieu of notice.",
            "Termination must follow due process — arbitrary dismissal may be challenged.",
            "Gig workers may have specific protections under the Code on Social Security, 2020.",
            # TODO: verify gig worker provisions under Code on Social Security, 2020
        ],
        DocumentType.CONSUMER: [
            "You have the right to file a consumer complaint for deficiency of service or defective goods.",
            "You can file online through e-Daakhil (https://edaakhil.nic.in).",
            "No court fee for claims up to ₹5 lakh at the District Consumer Forum.",
            "You can file in the District Forum where you reside or where the transaction occurred.",
            "You are entitled to compensation for mental agony and harassment caused by deficiency.",
            "E-commerce platforms are liable for the products sold through them under E-Commerce Rules, 2020.",
            # TODO: verify Consumer Protection Act, 2019 Section 34 jurisdiction rules
        ],
        DocumentType.UNKNOWN: [
            "You have the right to seek legal aid if you meet NALSA eligibility criteria.",
            "Please consult a qualified legal professional for advice specific to your situation.",
        ],
    }

    return rights_map.get(doc_type, rights_map[DocumentType.UNKNOWN])


def _get_default_nalsa_categories() -> list[str]:
    """Default NALSA free legal aid eligibility categories."""
    # Source: NALSA (National Legal Services Authority) — Section 12, Legal Services Authorities Act, 1987
    # TODO: verify complete list against https://nalsa.gov.in
    return [
        "Members of Scheduled Castes or Scheduled Tribes",
        "Victims of trafficking in human beings or forced labour (begar)",
        "Women and children",
        "Persons with disability as defined in the Rights of Persons with Disabilities Act, 2016",
        "Persons under circumstances of undeserved want (annual income below state threshold)",
        "Industrial workmen",
        "Persons in custody (including protective custody)",
        "Victims of mass disaster, ethnic violence, caste atrocity, flood, drought, earthquake, or industrial disaster",
        "Persons with mental illness or otherwise disabled, as defined under relevant legislation",
    ]
